export enum EventEnum {
  MAP_LOADED = 'MAP_LOADED',

  START_GAME_SCENE = 'START_GAME_SCENE',
  START_LAND_SCENE = 'START_LAND_SCENE',

  SET_ZOOM = 'SET_ZOOM',

  SET_GAME_MODE = 'SET_GAME_MODE',
  SET_HOTBAR_PLANTATION = 'SET_HOTBAR_PLANTATION',

  SELECT_BLOCK = 'SELECT_BLOCK',
  PLANT = 'PLANT',

  ON_CLICK_BLOCK_SELECT = 'ON_CLICK_BLOCK_SELECT',
  ON_CLICK_BLOCK_DESELECT = 'ON_CLICK_BLOCK_DESELECT',

  ON_CLICK_BOAT_SELECT = 'ON_CLICK_BOAT_SELECT',
  ON_CLICK_BOAT_DESELECT = 'ON_CLICK_BOAT_DESELECT',

  ON_CLICK_STRUCT_SELECT = 'ON_CLICK_STRUCT_SELECT',
  ON_CLICK_STRUCT_DESELECT = 'ON_CLICK_STRUCT_DESELECT',

  DESELECT_ALL = 'ON_CLICK_BOAT_DESELECT',

  UPDATE_LAND_INVENTORY = 'UPDATE_LAND_INVENTORY',
  UPDATE_BLOCK_INVENTORY = 'UPDATE_BLOCK_INVENTORY',
  UPDATE_STRUCT_INVENTORY = 'UPDATE_STRUCT_INVENTORY',
  UPDATE_DECORATION_INVENTORY = 'UPDATE_DECORATION_INVENTORY',
  UPDATE_PLANTATION_INVENTORY = 'UPDATE_PLANTATION_INVENTORY',

  FISH = 'FISH',

  VISIT = 'VISIT',
  RETURN = 'RETURN',
}
